//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progamming {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGUI() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Progamming.ResourceGUI", typeof(ResourceGUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &amp;Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_EDIT_ENG {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_EDIT_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정(&amp;E)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_EDIT_KOR {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_EDIT_KOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_FILE_ENG {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_FILE_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일(&amp;F)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_FILE_KOR {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_FILE_KOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_HELP_ENG {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_HELP_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말(&amp;H)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_HELP_KOR {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_HELP_KOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Resources과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_RESOURCES_ENG {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_RESOURCES_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리소스(&amp;R)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_RESOURCES_KOR {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_RESOURCES_KOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R&amp;un과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_RUN_ENG {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_RUN_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행(&amp;u)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_RUN_KOR {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_RUN_KOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Script과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_SCRIPTS_ENG {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_SCRIPTS_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스크립트(&amp;S)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_SCRIPTS_KOR {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_SCRIPTS_KOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_WINDOW_ENG {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_WINDOW_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   윈도우(&amp;W)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_MENUSTRIP_WINDOW_KOR {
            get {
                return ResourceManager.GetString("TEXT_MENUSTRIP_WINDOW_KOR", resourceCulture);
            }
        }
    }
}
